import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SQLiteProvider, useSQLiteContext } from 'expo-sqlite';
import { addGrade, addInventory, addManualItem, changeInventory, deleteGrade, deleteInventory, deleteManualItem, exportData, listAcademic, listGrades, listInventory, listSubjects, toggleAcademicItem, updateGrade, updateInventory, updateManualItem } from './src/db';
import { MockPronoteApi, syncPronote } from './src/pronote';
import { scheduleEveningReminder } from './src/notifications';
import { t, type Locale } from './src/i18n';
import type { AcademicItem, AcademicType, Grade, GradeType, InventoryItem, Subject } from './src/types';

const api = new MockPronoteApi();
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const isoDefault = () => { const d = new Date(); d.setMinutes(0,0,0); return d.toISOString().slice(0,16); };
const formatDate = (v:string, locale:Locale) => new Date(v).toLocaleString(locale==='fr'?'fr-FR':'en-US',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});

function AppContent(){
  const db=useSQLiteContext();
  const [tab,setTab]=useState<'home'|'room'|'planner'|'grades'|'settings'>('home');
  const [locale,setLocale]=useState<Locale>('fr');
  const [items,setItems]=useState<AcademicItem[]>([]); const [inventory,setInventory]=useState<InventoryItem[]>([]); const [grades,setGrades]=useState<Grade[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]);
  const [inventoryForm,setInventoryForm]=useState<InventoryItem|null|false>(false); const [academicForm,setAcademicForm]=useState<AcademicItem|null|false>(false); const [gradeForm,setGradeForm]=useState<Grade|null|false>(false);
  const refresh=async()=>{const [a,i,g,s]=await Promise.all([listAcademic(db),listInventory(db),listGrades(db),listSubjects(db)]);setItems(a);setInventory(i);setGrades(g);setSubjects(s);};
  useEffect(()=>{refresh().catch(e=>Alert.alert('Erreur',String(e)));},[]);
  const subjectMap=useMemo(()=>Object.fromEntries(subjects.map(s=>[s.id,s])),[subjects]);
  const upcoming=items.filter(x=>new Date(x.startsAt).getTime()>=Date.now()).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));
  const sync=async()=>{try{const from=new Date().toISOString(),to=new Date(Date.now()+7*86400000).toISOString();const n=await syncPronote(api,db,from,to);await refresh();Alert.alert('Pronote',`${n} éléments synchronisés.`);}catch(e){Alert.alert('Pronote',String(e));}};
  const reminder=async()=>{const text=upcoming.slice(0,5).map(x=>`• ${x.title}`).join('\n')||'Aucun élément prévu.';const ok=await scheduleEveningReminder(text);Alert.alert(t(locale,'reminder'),ok?'Rappel quotidien activé à 19h.':'Permission de notification refusée.');};
  const nav=['home','room','planner','grades','settings'] as const;
  return <SafeAreaView style={S.root}>
    <View style={S.header}><Text style={S.logo}>Student Planner</Text><Text style={S.muted}>{new Date().toLocaleDateString(locale==='fr'?'fr-FR':'en-US',{weekday:'short',day:'numeric',month:'short'})}</Text></View>
    <ScrollView contentContainerStyle={S.content}>
      {tab==='home'&&<Home locale={locale} items={upcoming} inventory={inventory} subjects={subjectMap} onSync={sync} onReminder={reminder}/>} 
      {tab==='room'&&<Room locale={locale} items={inventory} onAdd={()=>setInventoryForm(null)} onEdit={setInventoryForm} onDelete={async id=>{await deleteInventory(db,id);refresh();}} onChange={async(id,d)=>{await changeInventory(db,id,d);refresh();}}/>}
      {tab==='planner'&&<Planner locale={locale} items={items} subjects={subjectMap} onAdd={()=>setAcademicForm(null)} onEdit={setAcademicForm} onDelete={async id=>{await deleteManualItem(db,id);refresh();}} onToggle={async id=>{await toggleAcademicItem(db,id);refresh();}} onSync={sync}/>} 
      {tab==='grades'&&<Grades locale={locale} grades={grades} subjects={subjects} onAdd={()=>setGradeForm(null)} onEdit={setGradeForm} onDelete={async id=>{await deleteGrade(db,id);refresh();}}/>}
      {tab==='settings'&&<Settings locale={locale} setLocale={setLocale} onReminder={reminder} onExport={async()=>{const data=await exportData(db);Alert.alert(t(locale,'exportData'),JSON.stringify(data,null,2));}}/>}
    </ScrollView>
    <View style={S.tabs}>{nav.map(x=><Pressable key={x} style={S.tab} onPress={()=>setTab(x)}><Text style={[S.tabText,tab===x&&S.active]}>{t(locale,x)}</Text></Pressable>)}</View>
    <InventoryModal visible={inventoryForm!==false} initial={inventoryForm||undefined} locale={locale} onClose={()=>setInventoryForm(false)} onSave={async x=>{x.id=x.id||uid();if(inventoryForm&&inventoryForm!==null)await updateInventory(db,x);else await addInventory(db,x);setInventoryForm(false);await refresh();}}/>
    <AcademicModal visible={academicForm!==false} initial={academicForm||undefined} locale={locale} subjects={subjects} onClose={()=>setAcademicForm(false)} onSave={async x=>{x.id=x.id||uid();if(academicForm&&academicForm!==null)await updateManualItem(db,x);else await addManualItem(db,x);setAcademicForm(false);await refresh();}}/>
    <GradeModal visible={gradeForm!==false} initial={gradeForm||undefined} locale={locale} subjects={subjects} onClose={()=>setGradeForm(false)} onSave={async x=>{x.id=x.id||uid();if(gradeForm&&gradeForm!==null)await updateGrade(db,x);else await addGrade(db,x);setGradeForm(false);await refresh();}}/>
  </SafeAreaView>;
}

function Home(p:{locale:Locale,items:AcademicItem[],inventory:InventoryItem[],subjects:Record<string,Subject>,onSync:()=>void,onReminder:()=>void}){return <><Text style={S.title}>{p.locale==='fr'?'Bonjour':'Hello'}</Text><Text style={S.subtitle}>{p.locale==='fr'?'Ton tableau de bord étudiant.':'Your student dashboard.'}</Text><View style={S.actions}><Pressable style={S.primary} onPress={p.onSync}><Text style={S.primaryText}>{t(p.locale,'sync')}</Text></Pressable><Pressable style={S.secondary} onPress={p.onReminder}><Text style={S.secondaryText}>{t(p.locale,'reminder')}</Text></Pressable></View><Text style={S.section}>{t(p.locale,'upcoming')}</Text>{p.items.length?p.items.slice(0,6).map(x=><Card key={x.id}><View style={S.row}><View style={{flex:1}}><Text style={S.cardTitle}>{x.title}</Text><Text style={S.muted}>{formatDate(x.startsAt,p.locale)}{x.location?` · ${x.location}`:''}</Text>{x.subjectId&&<Text style={{color:p.subjects[x.subjectId]?.color,fontWeight:'700'}}>{p.subjects[x.subjectId]?.name}</Text>}</View><Text style={S.badge}>{x.origin==='pronote'?t(p.locale,'pronote'):t(p.locale,'manual')}</Text></View></Card>):<Card><Text>{t(p.locale,'noEvents')}</Text></Card>}<Text style={S.section}>{t(p.locale,'lowStock')}</Text>{p.inventory.filter(x=>x.quantity<=x.lowStockThreshold).map(x=><Card key={x.id}><Text style={S.cardTitle}>{x.name}</Text><Text style={S.muted}>{x.quantity} / seuil {x.lowStockThreshold}</Text></Card>)}</>}

function Room(p:{locale:Locale,items:InventoryItem[],onAdd:()=>void,onEdit:(x:InventoryItem)=>void,onDelete:(id:string)=>void,onChange:(id:string,d:number)=>void}){return <><View style={S.row}><View><Text style={S.title}>{t(p.locale,'room')}</Text><Text style={S.subtitle}>Inventaire local</Text></View><Pressable style={S.primarySmall} onPress={p.onAdd}><Text style={S.primaryText}>+ {t(p.locale,'add')}</Text></Pressable></View>{p.items.map(x=><Card key={x.id}><View style={S.row}><View style={{flex:1}}><Text style={S.cardTitle}>{x.name}</Text><Text style={S.muted}>{x.category} · seuil {x.lowStockThreshold}</Text></View><View style={S.stepper}><Pressable style={S.circle} onPress={()=>p.onChange(x.id,-1)}><Text>−</Text></Pressable><Text style={S.qty}>{x.quantity}</Text><Pressable style={S.circle} onPress={()=>p.onChange(x.id,1)}><Text>+</Text></Pressable></View></View><View style={S.inlineActions}><Pressable onPress={()=>p.onEdit(x)}><Text style={S.link}>{t(p.locale,'edit')}</Text></Pressable><Pressable onPress={()=>p.onDelete(x.id)}><Text style={S.danger}>{t(p.locale,'delete')}</Text></Pressable></View></Card>)}</>}

function Planner(p:{locale:Locale,items:AcademicItem[],subjects:Record<string,Subject>,onAdd:()=>void,onEdit:(x:AcademicItem)=>void,onDelete:(id:string)=>void,onToggle:(id:string)=>void,onSync:()=>void}){return <><View style={S.row}><View><Text style={S.title}>{t(p.locale,'planner')}</Text><Text style={S.subtitle}>Cours, devoirs, khôlles et événements</Text></View><Pressable style={S.primarySmall} onPress={p.onAdd}><Text style={S.primaryText}>+ {t(p.locale,'add')}</Text></Pressable></View><Pressable style={S.secondary} onPress={p.onSync}><Text style={S.secondaryText}>{t(p.locale,'sync')}</Text></Pressable>{p.items.sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).map(x=><Card key={x.id}><View style={S.row}><Pressable style={{flex:1}} onPress={()=>x.origin==='manual'&&p.onToggle(x.id)}><Text style={[S.cardTitle,x.completed&&S.strike]}>{x.completed?'✓ ':''}{x.title}</Text><Text style={S.muted}>{formatDate(x.startsAt,p.locale)}{x.location?` · ${x.location}`:''}</Text>{x.subjectId&&<Text style={{color:p.subjects[x.subjectId]?.color,fontWeight:'700'}}>{p.subjects[x.subjectId]?.name}</Text>}</Pressable><Text style={S.badge}>{x.origin==='pronote'?t(p.locale,'pronote'):t(p.locale,'manual')}</Text></View>{x.description&&<Text style={S.muted}>{x.description}</Text>}{x.origin==='manual'&&<View style={S.inlineActions}><Pressable onPress={()=>p.onEdit(x)}><Text style={S.link}>{t(p.locale,'edit')}</Text></Pressable><Pressable onPress={()=>p.onDelete(x.id)}><Text style={S.danger}>{t(p.locale,'delete')}</Text></Pressable></View>}</Card>)}</>}

function Grades(p:{locale:Locale,grades:Grade[],subjects:Subject[],onAdd:()=>void,onEdit:(x:Grade)=>void,onDelete:(id:string)=>void}){const avgs=p.subjects.map(s=>{const gs=p.grades.filter(g=>g.subjectId===s.id);const den=gs.reduce((a,g)=>a+g.coefficient,0);return {s,avg:den?gs.reduce((a,g)=>a+g.value*g.coefficient,0)/den:null};});const allDen=p.grades.reduce((a,g)=>a+g.coefficient,0);const global=allDen?p.grades.reduce((a,g)=>a+g.value*g.coefficient,0)/allDen:null;return <><View style={S.row}><View><Text style={S.title}>{t(p.locale,'grades')}</Text><Text style={S.subtitle}>{t(p.locale,'globalAverage')}: {global==null?'—':`${global.toFixed(2)}/20`}</Text></View><Pressable style={S.primarySmall} onPress={p.onAdd}><Text style={S.primaryText}>+ {t(p.locale,'add')}</Text></Pressable></View>{avgs.map(x=><Card key={x.s.id}><View style={S.row}><Text style={S.cardTitle}>{x.s.name}</Text><Text style={S.qty}>{x.avg==null?'—':`${x.avg.toFixed(2)}/20`}</Text></View></Card>)}<Text style={S.section}>Détail</Text>{p.grades.map(g=><Card key={g.id}><View style={S.row}><View style={{flex:1}}><Text style={S.cardTitle}>{g.value}/20 × {g.coefficient} · {g.type}</Text><Text style={S.muted}>{p.subjects.find(s=>s.id===g.subjectId)?.name} · {g.date}</Text>{g.note&&<Text style={S.muted}>{g.note}</Text>}</View><View><Pressable onPress={()=>p.onEdit(g)}><Text style={S.link}>{t(p.locale,'edit')}</Text></Pressable><Pressable onPress={()=>p.onDelete(g.id)}><Text style={S.danger}>{t(p.locale,'delete')}</Text></Pressable></View></View></Card>)}</>}

function Settings(p:{locale:Locale,setLocale:(l:Locale)=>void,onReminder:()=>void,onExport:()=>void}){return <><Text style={S.title}>{t(p.locale,'settings')}</Text><Text style={S.subtitle}>Configuration de l'application</Text><Card><Text style={S.cardTitle}>{t(p.locale,'language')}</Text><View style={S.actions}><Pressable style={p.locale==='fr'?S.primary:S.secondary} onPress={()=>p.setLocale('fr')}><Text style={p.locale==='fr'?S.primaryText:S.secondaryText}>Français</Text></Pressable><Pressable style={p.locale==='en'?S.primary:S.secondary} onPress={()=>p.setLocale('en')}><Text style={p.locale==='en'?S.primaryText:S.secondaryText}>English</Text></Pressable></View></Card><Card><Text style={S.cardTitle}>Pronote</Text><Text style={S.muted}>Mock actif. Le futur adaptateur réel pourra remplacer cette implémentation sans modifier la base locale.</Text></Card><Card><Text style={S.cardTitle}>{t(p.locale,'reminder')}</Text><Pressable style={S.primary} onPress={p.onReminder}><Text style={S.primaryText}>19:00</Text></Pressable></Card><Card><Text style={S.cardTitle}>{t(p.locale,'exportData')}</Text><Text style={S.muted}>{t(p.locale,'localOnly')}</Text><Pressable style={S.secondary} onPress={p.onExport}><Text style={S.secondaryText}>{t(p.locale,'exportData')}</Text></Pressable><Text style={S.muted}>L'export affiche actuellement le JSON versionné afin de pouvoir ajouter ensuite un partage/fichier natif.</Text></Card></>}

function Field({label,value,onChange,keyboard='default'}:{label:string,value:string,onChange:(x:string)=>void,keyboard?:any}){return <View style={{marginBottom:10}}><Text style={S.label}>{label}</Text><TextInput style={S.input} value={value} onChangeText={onChange} keyboardType={keyboard} placeholder={label}/></View>}
function ModalShell({visible,title,onClose,children,onSave}:{visible:boolean,title:string,onClose:()=>void,children:React.ReactNode,onSave:()=>void}){return <Modal visible={visible} transparent animationType="slide"><View style={S.overlay}><View style={S.modal}><Text style={S.modalTitle}>{title}</Text><ScrollView>{children}</ScrollView><View style={S.actions}><Pressable style={S.secondary} onPress={onClose}><Text style={S.secondaryText}>Annuler</Text></Pressable><Pressable style={S.primary} onPress={onSave}><Text style={S.primaryText}>Enregistrer</Text></Pressable></View></View></View></Modal>}
function InventoryModal(p:{visible:boolean,initial?:InventoryItem,locale:Locale,onClose:()=>void,onSave:(x:InventoryItem)=>void}){const [x,setX]=useState<InventoryItem>({id:'',name:'',category:'Papeterie',quantity:0,lowStockThreshold:1});useEffect(()=>{setX(p.initial?{...p.initial}:{id:'',name:'',category:'Papeterie',quantity:0,lowStockThreshold:1})},[p.initial,p.visible]);return <ModalShell visible={p.visible} title={p.initial?t(p.locale,'edit'):t(p.locale,'add')} onClose={p.onClose} onSave={()=>{if(!x.name.trim())return Alert.alert('Erreur','Nom requis');p.onSave(x)}}><Field label={t(p.locale,'name')} value={x.name} onChange={v=>setX({...x,name:v})}/><Field label={t(p.locale,'category')} value={x.category} onChange={v=>setX({...x,category:v})}/><Field label={t(p.locale,'quantity')} value={String(x.quantity)} keyboard="numeric" onChange={v=>setX({...x,quantity:Math.max(0,Number(v)||0)})}/><Field label={t(p.locale,'threshold')} value={String(x.lowStockThreshold)} keyboard="numeric" onChange={v=>setX({...x,lowStockThreshold:Math.max(0,Number(v)||0)})}/></ModalShell>}
function AcademicModal(p:{visible:boolean,initial?:AcademicItem,locale:Locale,subjects:Subject[],onClose:()=>void,onSave:(x:AcademicItem)=>void}){const blank=():AcademicItem=>({id:'',origin:'manual',type:'event',title:'',subjectId:p.subjects[0]?.id,startsAt:isoDefault(),endsAt:new Date(Date.now()+3600000).toISOString().slice(0,16),completed:false});const [x,setX]=useState<AcademicItem>(blank());useEffect(()=>setX(p.initial?{...p.initial}:blank()),[p.initial,p.visible]);return <ModalShell visible={p.visible} title={p.initial?t(p.locale,'edit'):t(p.locale,'add')} onClose={p.onClose} onSave={()=>{if(!x.title.trim())return Alert.alert('Erreur','Titre requis');p.onSave(x)}}><Field label={t(p.locale,'title')} value={x.title} onChange={v=>setX({...x,title:v})}/><Text style={S.label}>{t(p.locale,'type')}</Text><View style={S.wrap}>{(['event','assignment','kholle','exam','course'] as AcademicType[]).map(v=><Pressable key={v} style={[S.choice,x.type===v&&S.choiceActive]} onPress={()=>setX({...x,type:v})}><Text>{v}</Text></Pressable>)}</View><Text style={S.label}>{t(p.locale,'subject')}</Text><View style={S.wrap}>{p.subjects.map(s=><Pressable key={s.id} style={[S.choice,x.subjectId===s.id&&S.choiceActive]} onPress={()=>setX({...x,subjectId:s.id})}><Text>{s.name}</Text></Pressable>)}</View><Field label="Début (YYYY-MM-DDTHH:mm)" value={x.startsAt} onChange={v=>setX({...x,startsAt:v})}/><Field label="Fin (YYYY-MM-DDTHH:mm)" value={x.endsAt} onChange={v=>setX({...x,endsAt:v})}/><Field label={t(p.locale,'location')} value={x.location||''} onChange={v=>setX({...x,location:v})}/><Field label={t(p.locale,'description')} value={x.description||''} onChange={v=>setX({...x,description:v})}/></ModalShell>}
function GradeModal(p:{visible:boolean,initial?:Grade,locale:Locale,subjects:Subject[],onClose:()=>void,onSave:(x:Grade)=>void}){const blank=():Grade=>({id:'',subjectId:p.subjects[0]?.id||'',type:'ds',value:0,coefficient:1,date:new Date().toISOString().slice(0,10)});const [x,setX]=useState<Grade>(blank());useEffect(()=>setX(p.initial?{...p.initial}:blank()),[p.initial,p.visible]);return <ModalShell visible={p.visible} title={p.initial?t(p.locale,'edit'):t(p.locale,'add')} onClose={p.onClose} onSave={()=>{if(x.value<0||x.value>20)return Alert.alert('Erreur','La note doit être comprise entre 0 et 20.');if(x.coefficient<=0)return Alert.alert('Erreur','Le coefficient doit être positif.');p.onSave(x)}}><Text style={S.label}>{t(p.locale,'subject')}</Text><View style={S.wrap}>{p.subjects.map(s=><Pressable key={s.id} style={[S.choice,x.subjectId===s.id&&S.choiceActive]} onPress={()=>setX({...x,subjectId:s.id})}><Text>{s.name}</Text></Pressable>)}</View><Text style={S.label}>{t(p.locale,'type')}</Text><View style={S.wrap}>{(['ds','kholle','exam','homework','other'] as GradeType[]).map(v=><Pressable key={v} style={[S.choice,x.type===v&&S.choiceActive]} onPress={()=>setX({...x,type:v})}><Text>{v}</Text></Pressable>)}</View><Field label={t(p.locale,'value')} value={String(x.value)} keyboard="decimal-pad" onChange={v=>setX({...x,value:Number(v.replace(',','.'))||0})}/><Field label={t(p.locale,'coefficient')} value={String(x.coefficient)} keyboard="decimal-pad" onChange={v=>setX({...x,coefficient:Number(v.replace(',','.'))||1})}/><Field label={t(p.locale,'date')} value={x.date} onChange={v=>setX({...x,date:v})}/><Field label="Note" value={x.note||''} onChange={v=>setX({...x,note:v})}/></ModalShell>}
function Card({children}:{children:React.ReactNode}){return <View style={S.card}>{children}</View>}

export default function App(){return <SQLiteProvider databaseName="student-planner.db" onInit={initDb}><AppContent/></SQLiteProvider>}
import { initDb } from './src/db';

const S=StyleSheet.create({root:{flex:1,backgroundColor:'#f6f7fb'},header:{padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},logo:{fontSize:20,fontWeight:'800'},content:{padding:20,paddingBottom:110},title:{fontSize:30,fontWeight:'800',marginTop:6},subtitle:{fontSize:15,color:'#6b7280',marginTop:4,marginBottom:18},section:{fontSize:20,fontWeight:'800',marginTop:24,marginBottom:10},muted:{color:'#6b7280',marginTop:4},card:{backgroundColor:'#fff',borderRadius:16,padding:16,marginBottom:10,borderWidth:1,borderColor:'#e5e7eb'},cardTitle:{fontSize:16,fontWeight:'700'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},actions:{flexDirection:'row',gap:10,marginBottom:8},primary:{backgroundColor:'#111827',padding:13,borderRadius:12,alignItems:'center',flex:1},primarySmall:{backgroundColor:'#111827',padding:10,borderRadius:10},primaryText:{color:'#fff',fontWeight:'700'},secondary:{backgroundColor:'#e5e7eb',padding:13,borderRadius:12,alignItems:'center',flex:1},secondaryText:{color:'#111827',fontWeight:'700'},stepper:{flexDirection:'row',alignItems:'center',gap:9},circle:{width:34,height:34,borderRadius:17,backgroundColor:'#eef0f5',alignItems:'center',justifyContent:'center'},qty:{fontWeight:'800',minWidth:50,textAlign:'center',fontSize:17},badge:{backgroundColor:'#eef0f5',paddingHorizontal:8,paddingVertical:5,borderRadius:8,fontSize:11},tabs:{position:'absolute',bottom:0,left:0,right:0,height:76,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e5e7eb',flexDirection:'row',paddingTop:12},tab:{flex:1,alignItems:'center'},tabText:{fontSize:11,color:'#6b7280'},active:{color:'#111827',fontWeight:'800'},inlineActions:{flexDirection:'row',gap:20,marginTop:12},link:{fontWeight:'700'},danger:{fontWeight:'700',color:'#dc2626'},strike:{textDecorationLine:'line-through',color:'#9ca3af'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'flex-end'},modal:{backgroundColor:'#fff',borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,maxHeight:'90%'},modalTitle:{fontSize:22,fontWeight:'800',marginBottom:14},label:{fontWeight:'700',marginBottom:6,marginTop:5},input:{borderWidth:1,borderColor:'#d1d5db',borderRadius:10,padding:11,marginBottom:2},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:10},choice:{padding:9,borderRadius:9,backgroundColor:'#f3f4f6'},choiceActive:{backgroundColor:'#dbeafe'}});
